name = "serial-mutation-engine"
pages_build_output_dir = "build"

compatibility_date = "2025-10-26"
compatibility_flags = ["streams_enable_constructors"]

[[kv_namespaces]]
binding = "SERIAL_CACHE"
id = "dd0a482ea34e4d56aaf32390502ffe4e"